/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.quantri;

import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import modul.HoaDonThue;
import controller.DongPhucController;
import controller.HoaDonThueController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import controller.TaiKhoanController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import modul.TaiKhoan; 
/**quantri
 *
 * @author This Pc
 */
public class QuanTriThueForm extends javax.swing.JFrame {
    private  String taiKhoan; 
    static  HoaDonThueController hdtc = new HoaDonThueController();
    static  DongPhucController tkdp = new DongPhucController();
    static  DefaultTableModel tblModel = new DefaultTableModel();
    static  TaiKhoanController tkcrl = new TaiKhoanController(); 
    /**
     * Creates new form ThueForm2
     */
    public QuanTriThueForm(String taiKhoan) throws IOException{
        initComponents();
         this.setLocationRelativeTo(null);
        this.taiKhoan=taiKhoan; 
        ViewInforAdmin();
        initTable();
        fillTable();
    }
    public void ViewInforAdmin() throws IOException{
        TaiKhoan tk = tkcrl.getTaiKhoan(taiKhoan); 
        txttenTk.setText(tk.getTenTK());
        
    } 
    
    private void initTable(){
        String[] columns = new String[]{"Mã thuê", "Size", "Số lượng", "Mã sinh viên", "Ngày thuê", "Ngày trả", "Đơn giá", "Tổng tiền", "Hạn"};
        tblModel.setColumnIdentifiers(columns);
        tbDonThue.setModel(tblModel);
        JScrollPane scrollPane = new JScrollPane();
        tbDonThue.setFillsViewportHeight(true);
    }
    private  void fillTable() throws IOException{
       tblModel.setRowCount(0);
        ArrayList<HoaDonThue> listT = hdtc.getListHoaDonThue();
        for (HoaDonThue z : listT) {
                tblModel.addRow(new Object[]{z.getMaThue(),z.getSize(), z.getsL(), z.getMaSinhVien(), z.getNgayThue(), z.getNgayTra(), z.getDonGia(), z.tongTien(), z.isCheckTra()});
        }
        tblModel.fireTableDataChanged();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDonThue = new javax.swing.JTable();
        btnCapNhatBang = new javax.swing.JButton();
        btnXoaDonThue = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        txttenTk = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("DANH SÁCH ĐƠN THUÊ");

        tbDonThue.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbDonThue.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã thuê", "Size", "Số lượng", "Mã sinh viên", "Ngày thuê", "Ngày trả", "Đơn giá", "Tổng tiền"
            }
        ));
        jScrollPane1.setViewportView(tbDonThue);

        btnCapNhatBang.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnCapNhatBang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/images.jpg"))); // NOI18N
        btnCapNhatBang.setText("Cập nhật bảng");
        btnCapNhatBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatBangActionPerformed(evt);
            }
        });

        btnXoaDonThue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnXoaDonThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icondelete16.png"))); // NOI18N
        btnXoaDonThue.setText("Xoá đơn thuê");
        btnXoaDonThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDonThueActionPerformed(evt);
            }
        });

        btnDong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconthoat16.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.jpg"))); // NOI18N
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txttenTk, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btnCapNhatBang)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaDonThue, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtTimKiem))
                        .addGap(18, 18, 18)
                        .addComponent(btnDong, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttenTk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCapNhatBang, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaDonThue)
                    .addComponent(btnDong))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXoaDonThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDonThueActionPerformed
        // TODO add your handling code here:
        int removeIndex = tbDonThue.getSelectedRow();
        if(removeIndex == -1)
            JOptionPane.showMessageDialog(rootPane, "Chưa chọn dòng cần xóa!", "Thông báo", JOptionPane.CLOSED_OPTION);
        else {
            int choice = JOptionPane.showConfirmDialog(this,
                "Xác nhận xóa đơn hàng?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                int row = tbDonThue.getSelectedRow();
                String maThue = tbDonThue.getModel().getValueAt(row, 0).toString();
                String size = tbDonThue.getModel().getValueAt(row, 1).toString();
                String soLuong = tbDonThue.getModel().getValueAt(row, 2).toString();
                String han = tbDonThue.getModel().getValueAt(row, 8).toString();
                int modelIndex = tbDonThue.convertRowIndexToModel(removeIndex);
                DefaultTableModel model = (DefaultTableModel)tbDonThue.getModel();
                model.removeRow(modelIndex);
                try {
                    hdtc.xoaHDThue(maThue);
                    if(han != "true")
                        DongPhucController.congDPTon(size, Integer.parseInt(soLuong));
                } catch (IOException ex) {
                }
                JOptionPane.showMessageDialog(null, "Bạn xóa thành công!", "Thông báo", JOptionPane.CLOSED_OPTION);
            }
        }
    }//GEN-LAST:event_btnXoaDonThueActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có muốn thoát?",
                "XÁC NHẬN", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION){
            return;
        }
        dispose();
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnCapNhatBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatBangActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ArrayList<HoaDonThue> listT = hdtc.getListHoaDonThue();
            for(HoaDonThue t : listT){
                String maThue = t.getMaThue();
                String size = t.getSize();
                int soLuong = t.getsL();
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
                Date d1 = new Date();
                Date d2 = null;
                try {
                    d2 = sdf.parse(t.getNgayTra());
                } catch (ParseException e) {
                }
                long diff = d2.getTime() - d1.getTime();
                if(diff <= 0 && t.isCheckTra() != true){
                    DongPhucController.congDPTon(size, soLuong);
                    HoaDonThueController.checkTraTrue(maThue);
                }
                
            }
            fillTable();
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_btnCapNhatBangActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String maThue = txtTimKiem.getText();
        try {
            tblModel.setRowCount(0);
            HoaDonThue hdt = hdtc.getHoaDonThueByMaThue(maThue);
            if (hdt == null) {
                JOptionPane.showMessageDialog(rootPane, "Đơn hàng không hợp lệ!", "Thông báo", JOptionPane.CLOSED_OPTION);
                return;
            }
            tblModel.addRow(new Object[]{hdt.getMaThue(),hdt.getSize(), hdt.getsL(), hdt.getMaSinhVien(), hdt.getNgayThue(), hdt.getNgayTra(), hdt.getDonGia(), hdt.tongTien(), hdt.isCheckTra()});
            tblModel.fireTableDataChanged();
            } catch (IOException ex) {
            }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanTriThueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanTriThueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanTriThueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanTriThueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatBang;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoaDonThue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb1;
    private javax.swing.JTable tbDonThue;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txttenTk;
    // End of variables declaration//GEN-END:variables
}
