/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sinhvien;

import modul.DanhGia;
import modul.SinhVien;
import controller.SinhVienController;
import controller.DanhGiaController;
import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DanhGiaForm extends javax.swing.JFrame {

    private String id;
    private String ma;
    DanhGiaController danhGiaController = new DanhGiaController();
    SinhVienController ttsv2 = new SinhVienController();

    ; 
    /**
     * Creates new form DanhGiaForm
     */
    //Truyền mã qua các form để dễ dàng đồng bộ
    public DanhGiaForm(String ma) throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ma = ma;
        viewInfor2();
    }

    public void viewInfor2() throws IOException {
        //Tìm đối tượng qua mã được truyền qua
        SinhVien sv = ttsv2.getSinhVienByMa(ma);
        txtMaSV1.setText(sv.getMaSinhVien());
        txtTenSV.setText(sv.getTenSinhVien());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_xoatrang = new javax.swing.JButton();
        btn_DangGia = new javax.swing.JButton();
        btn_Dong = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtMaSV1 = new javax.swing.JTextField();
        img_avatar = new javax.swing.JLabel();
        txtTenSV = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtnhanxet = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_GopY = new javax.swing.JTextArea();
        cb_dienDG = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rd_rathl1 = new javax.swing.JRadioButton();
        rd_hailong1 = new javax.swing.JRadioButton();
        rd_bt1 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rd_khonghl1 = new javax.swing.JRadioButton();
        rd_rathl2 = new javax.swing.JRadioButton();
        rd_hailonh2 = new javax.swing.JRadioButton();
        rd_bt2 = new javax.swing.JRadioButton();
        rd_khonghl2 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Thoat = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(630, 840));
        setSize(new java.awt.Dimension(500, 400));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("KHÁO SÁT ĐÁNH GIÁ");

        btn_xoatrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icondelete16.png"))); // NOI18N
        btn_xoatrang.setText("Xóa trắng");
        btn_xoatrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoatrangActionPerformed(evt);
            }
        });

        btn_DangGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconsave16.png"))); // NOI18N
        btn_DangGia.setText("Gửi");
        btn_DangGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangGiaActionPerformed(evt);
            }
        });

        btn_Dong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconthoat16.png"))); // NOI18N
        btn_Dong.setText("Đóng");
        btn_Dong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DongActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtMaSV1.setBackground(new java.awt.Color(204, 204, 204));
        txtMaSV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSV1ActionPerformed(evt);
            }
        });

        img_avatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/avatar1.jpg"))); // NOI18N

        txtTenSV.setBackground(new java.awt.Color(204, 204, 204));
        txtTenSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenSV)
                    .addComponent(img_avatar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMaSV1))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(img_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMaSV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setToolTipText("");

        txtnhanxet.setColumns(20);
        txtnhanxet.setRows(5);
        jScrollPane2.setViewportView(txtnhanxet);

        txt_GopY.setColumns(20);
        txt_GopY.setRows(5);
        jScrollPane1.setViewportView(txt_GopY);

        cb_dienDG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 điểm", "2 điểm", "3 điểm", "4 điểm", "5 điểm" }));
        cb_dienDG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_dienDGActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Đóng góp ý kiến");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Nhận xét");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Đánh giá ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Bạn có hài lòng về chất lượng đồng phục không?");

        buttonGroup1.add(rd_rathl1);
        rd_rathl1.setText("Rất hài lòng ");
        rd_rathl1.setToolTipText("");

        buttonGroup1.add(rd_hailong1);
        rd_hailong1.setText("Hài lòng ");
        rd_hailong1.setToolTipText("");

        buttonGroup1.add(rd_bt1);
        rd_bt1.setText("Bình thường");
        rd_bt1.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Bạn có hài lòng về chất lượng hệ thống không?");

        buttonGroup1.add(rd_khonghl1);
        rd_khonghl1.setText("Không hài lòng");
        rd_khonghl1.setToolTipText("");

        buttonGroup2.add(rd_rathl2);
        rd_rathl2.setText("Rất hài lòng ");

        buttonGroup2.add(rd_hailonh2);
        rd_hailonh2.setText("Hài lòng ");

        buttonGroup2.add(rd_bt2);
        rd_bt2.setText("Bình thường");

        buttonGroup2.add(rd_khonghl2);
        rd_khonghl2.setText("Không hài lòng ");

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("* Bắt buộc");

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("* Bắt buộc");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb_dienDG, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(rd_khonghl2)
                            .addComponent(rd_hailonh2)
                            .addComponent(rd_rathl2)
                            .addComponent(rd_khonghl1)
                            .addComponent(rd_hailong1)
                            .addComponent(rd_rathl1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rd_bt2)
                            .addComponent(rd_bt1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(rd_rathl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_hailong1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_bt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_khonghl1)
                .addGap(13, 13, 13)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(7, 7, 7)
                .addComponent(rd_rathl2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_hailonh2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_bt2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rd_khonghl2)
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_dienDG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        btn_Thoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/3596149.png"))); // NOI18N
        btn_Thoat.setText("Thoát");
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(86, 86, 86)
                .addComponent(btn_Thoat)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_xoatrang)
                        .addGap(49, 49, 49)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btn_DangGia, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btn_Dong)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Thoat)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_DangGia)
                        .addComponent(btn_xoatrang))
                    .addComponent(btn_Dong))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_DangGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangGiaActionPerformed
        //Lấy các dữ liệu từ form
        ma = "";
        Random rd = new Random();
        ma = "DG" + rd.nextInt(10000);
        String chatluongao = "";
        String chatluonghethong = "";
        String masv = txtMaSV1.getText();
        String diemdg = (String) cb_dienDG.getSelectedItem();
        String gopy = txt_GopY.getText();
        String nhanxet = txtnhanxet.getText();
        //Bắt lỗi chưa chọn Jradiobutton 
        if (rd_rathl1.isSelected()) {
            chatluongao = "Rất hài lòng";
        } else if (rd_hailong1.isSelected()) {
            chatluongao = "Hài lòng";
        } else if (rd_bt1.isSelected()) {
            chatluongao = "Bình thường";
        } else if (rd_khonghl1.isSelected()) {
            chatluongao = "Không hài lòng";
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cần đánh giá mức độ hài lòng với đồng phục", "Thông báo", JOptionPane.CLOSED_OPTION);
            return;
        }
        if (rd_rathl2.isSelected()) {
            chatluonghethong = "Rất hài lòng";
        } else if (rd_hailonh2.isSelected()) {
            chatluonghethong = "Hài lòng";
        } else if (rd_bt2.isSelected()) {
            chatluonghethong = "Bình thường";
        } else if (rd_khonghl2.isSelected()) {
            chatluonghethong = "Không hài lòng";
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cần đánh giá mức độ hài lòng với hệ thống", "Thông báo", JOptionPane.CLOSED_OPTION);
            return;
        }
        //Bắt lỗi để trống trường nhập liệu
        if (nhanxet.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhận xét gì ", "Thông báo", JOptionPane.CLOSED_OPTION);
            return;
        } else if (gopy.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa góp ý  ", "Thông báo", JOptionPane.CLOSED_OPTION);
        } else {

            try {
                DanhGia d = danhGiaController.getDanhGiaByMaSV(masv);
                //Bắt lỗi đã tồn tại khảo sát của sinh viên này 
                if (d != null) {
                    JOptionPane.showMessageDialog(rootPane, "Đánh giá của bạn đã tồn tại trong hệ thống", "Thông báo", JOptionPane.CLOSED_OPTION);
                    return;
                }
            } catch (IOException ex) {
                Logger.getLogger(DanhGiaForm.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                int choice = JOptionPane.showConfirmDialog(this,
                        "Bạn có chắc chắn gửi đánh giá có mã " + ma + " lên hệ thống?",
                        "Hỏi", JOptionPane.YES_NO_OPTION);
                if (choice == JOptionPane.YES_OPTION) {
                    //Gọi hàm thêm đánh giá của danhGiaController để thêm một đánh giá mới
                    DanhGia dg = new DanhGia(ma, masv, chatluongao, chatluonghethong, diemdg, nhanxet, gopy);
                    danhGiaController.themDanhGia(dg);
                } else {
                    return;

                }
            } catch (Exception e) {

            }
        }
    }//GEN-LAST:event_btn_DangGiaActionPerformed

    private void btn_xoatrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoatrangActionPerformed

        String emty = "";
        txt_GopY.setText(emty);
        txt_GopY.setBackground(null);
        txtnhanxet.setText(emty);
        txtnhanxet.setBackground(null);
        cb_dienDG.setSelectedIndex(0);


    }//GEN-LAST:event_btn_xoatrangActionPerformed

    private void txtTenSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSVActionPerformed

    private void txtMaSV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSV1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSV1ActionPerformed

    private void cb_dienDGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_dienDGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_dienDGActionPerformed

    private void btn_DongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DongActionPerformed

        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn đóng cửa số này?",
                "Hỏi", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
            dispose();

        } else {
            return;
        }
    }//GEN-LAST:event_btn_DongActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có muốn thoát?",
                "XÁC NHẬN", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION) {
            return;
        }
        System.exit(0);
    }//GEN-LAST:event_btn_ThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhGiaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhGiaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhGiaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhGiaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_DangGia;
    private javax.swing.JButton btn_Dong;
    private javax.swing.JButton btn_Thoat;
    private javax.swing.JButton btn_xoatrang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cb_dienDG;
    private javax.swing.JLabel img_avatar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rd_bt1;
    private javax.swing.JRadioButton rd_bt2;
    private javax.swing.JRadioButton rd_hailong1;
    private javax.swing.JRadioButton rd_hailonh2;
    private javax.swing.JRadioButton rd_khonghl1;
    private javax.swing.JRadioButton rd_khonghl2;
    private javax.swing.JRadioButton rd_rathl1;
    private javax.swing.JRadioButton rd_rathl2;
    private javax.swing.JTextField txtMaSV1;
    private javax.swing.JTextField txtTenSV;
    private javax.swing.JTextArea txt_GopY;
    private javax.swing.JTextArea txtnhanxet;
    // End of variables declaration//GEN-END:variables
}
