/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.sinhvien;

import modul.HoaDonThue; 
import modul.SinhVien;
import controller.SinhVienController; 
import controller.DongPhucController; 
import controller.HoaDonThueController;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author This Pc
 */
public class ThueForm extends javax.swing.JFrame {
    private  String ma; 
     SinhVienController ttsv2 = new SinhVienController();
    /**
     * Creates new form ThueForm1
     */
    public ThueForm(String ma) throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ma = ma; 
        ViewInfor6();
    }
    public  void ViewInfor6() throws IOException{
        SinhVien sv = ttsv2.getSinhVienByMa(ma);
        txtmasv.setText(sv.getMaSinhVien());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnThue = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        lbSize = new javax.swing.JLabel();
        lbSoLuong = new javax.swing.JLabel();
        lbTongTien = new javax.swing.JLabel();
        lbNgayThue = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();
        txtNgayThue = new java.awt.TextField();
        txtSoLuong = new java.awt.TextField();
        txtTongTien = new javax.swing.JTextField();
        lbNgayTra = new javax.swing.JLabel();
        txtNgayTra = new java.awt.TextField();
        cbSize = new javax.swing.JComboBox<>();
        lbDonGia = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        btnTinhTongTien = new javax.swing.JButton();
        lbNgayTra1 = new javax.swing.JLabel();
        txtmasv = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnThue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnThue.setText("Thuê");
        btnThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThueActionPerformed(evt);
            }
        });

        btnDong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iconthoat16.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        lbSize.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbSize.setText("Size:");

        lbSoLuong.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbSoLuong.setText("Số lượng:");

        lbTongTien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbTongTien.setText("Tổng tiền:");

        lbNgayThue.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbNgayThue.setText("Ngày thuê:");

        lb1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lb1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb1.setText("ĐƠN THUÊ ĐỒNG PHỤC THỂ THAO");

        txtTongTien.setEditable(false);
        txtTongTien.setBackground(new java.awt.Color(255, 255, 255));
        txtTongTien.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbNgayTra.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbNgayTra.setText("Ngày trả:");

        cbSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn size", "X", "XS", "S", "M", "L", "XL", "XXL" }));
        cbSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSizeActionPerformed(evt);
            }
        });

        lbDonGia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbDonGia.setText("Đơn giá:");

        txtDonGia.setEditable(false);
        txtDonGia.setBackground(new java.awt.Color(255, 255, 255));
        txtDonGia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnTinhTongTien.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btnTinhTongTien.setText("Tính tổng tiền");
        btnTinhTongTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTongTienActionPerformed(evt);
            }
        });

        lbNgayTra1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbNgayTra1.setText("Mã sinh viên");

        txtmasv.setEditable(false);
        txtmasv.setBackground(new java.awt.Color(255, 255, 255));
        txtmasv.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTinhTongTien)
                        .addGap(70, 70, 70)
                        .addComponent(btnThue, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnDong)
                        .addGap(78, 78, 78)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNgayTra1)
                    .addComponent(lbDonGia)
                    .addComponent(lbNgayTra)
                    .addComponent(lbNgayThue)
                    .addComponent(lbSoLuong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNgayThue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNgayTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDonGia)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbTongTien)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(lbSize)
                                .addGap(57, 57, 57)
                                .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtmasv))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbSize)
                            .addComponent(cbSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lbSoLuong))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(txtNgayThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbNgayThue, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNgayTra1)
                    .addComponent(txtmasv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDonGia)
                    .addComponent(lbTongTien)
                    .addComponent(txtDonGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDong)
                    .addComponent(btnThue)
                    .addComponent(btnTinhTongTien))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThueActionPerformed
        
        String maSinhVien = txtmasv.getText(); 
        String size = (String)cbSize.getSelectedItem(); 
        String soLuong = txtSoLuong.getText();
        String ngayThue = txtNgayThue.getText();
        String ngayTra = txtNgayTra.getText();
        
        if(soLuong.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập số lượng!", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        else if(size.contains("Chọn size") == true){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn size!", "Thông báo", JOptionPane.CLOSED_OPTION);    
        }
        else if(ngayThue.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập ngày thuê!", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        else if(ngayTra.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập ngày trả!", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        else if(!ngayThue.isBlank() && !ngayTra.isBlank()){
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            Date dateThue = null;
            Date dateTra = null;
            Date dateNow = new Date();
            try {
                dateThue = sdf.parse(ngayThue);
                dateTra = sdf.parse(ngayTra);
            } catch (ParseException e) {
            }
            long diffNow1 = dateThue.getTime() - dateNow.getTime();
            long diffNow2 = dateTra.getTime() - dateNow.getTime();
            long diff = dateTra.getTime() - dateThue.getTime();
            if(diffNow1 <= 0 || diffNow2 <=0) JOptionPane.showMessageDialog(rootPane, "Ngày thuê hoặc ngày trả không hợp lệ!", "Thông báo", JOptionPane.CLOSED_OPTION);
            else if(diff <=0)
                JOptionPane.showMessageDialog(rootPane, "Ngày trả phải lớn hơn ngày thuê!", "Thông báo", JOptionPane.CLOSED_OPTION);
            else {
                try {
                    HoaDonThue dpt = new HoaDonThue(size, Integer.parseInt(soLuong), ngayThue, ngayTra, maSinhVien);
                    HoaDonThueController.themHDThue(dpt);
                    DongPhucController.truDPTon(size, Integer.parseInt(soLuong));
                    JOptionPane.showMessageDialog(rootPane, "Bạn đã thuê thành công  ", "Thông báo", JOptionPane.CLOSED_OPTION);
                } catch (Exception e) {
                }
            }
       }
       
    }//GEN-LAST:event_btnThueActionPerformed

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this,
                "Bạn có muốn thoát?",
                "xÁC NHẬN", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.NO_OPTION){
            return;
        }
        dispose(); 
    }//GEN-LAST:event_btnDongActionPerformed

    private void cbSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSizeActionPerformed
        // TODO add your handling code here:
        switch((String)cbSize.getSelectedItem()){
            case "X":
                txtDonGia.setText("10000");
                break;
            case "XS":
                txtDonGia.setText("11000");
                break;
            case "S":
                txtDonGia.setText("12000");
                break;
            case "M":
                txtDonGia.setText("13000");
                break;
            case "L":
                txtDonGia.setText("14000");
                break;
            case "XL":
                txtDonGia.setText("15000");
                break;
            case "XXL":
                txtDonGia.setText("16000");
                break;
        }
    }//GEN-LAST:event_cbSizeActionPerformed

    private void btnTinhTongTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTongTienActionPerformed
        // TODO add your handling code here:
        String size = (String)cbSize.getSelectedItem();
        String soLuong = txtSoLuong.getText();
        String donGia = txtDonGia.getText();
        String ngayThue = txtNgayThue.getText();
        String ngayTra = txtNgayTra.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            Date dateThue = null;
            Date dateTra = null;
            Date dateNow = new Date(); 
        if(soLuong.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập số lượng!", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        else if(size.contains("Chọn size") == true){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa chọn size!", "Thông báo", JOptionPane.CLOSED_OPTION);    
        }
        else if(ngayThue.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập ngày thuê!", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        else if(ngayTra.isBlank()){
            JOptionPane.showMessageDialog(rootPane, "Bạn chưa nhập ngày trả!", "Thông báo", JOptionPane.CLOSED_OPTION);
        }
        else{
            try {
                dateThue = sdf.parse(ngayThue);
                dateTra = sdf.parse(ngayTra);
            } catch (ParseException e) {
            }
            long diffNow1 = dateThue.getTime() - dateNow.getTime();
            long diffNow2 = dateTra.getTime() - dateNow.getTime();
            long diff = (dateTra.getTime() - dateThue.getTime()) / (24 * 3600 * 1000);
            if(diffNow1 <= 0 || diffNow2 <=0) JOptionPane.showMessageDialog(rootPane, "Ngày thuê hoặc ngày trả không hợp lệ!", "Thông báo", JOptionPane.CLOSED_OPTION);
            else if(diff <=0)
                JOptionPane.showMessageDialog(rootPane, "Ngày trả phải lớn hơn ngày thuê!", "Thông báo", JOptionPane.CLOSED_OPTION);
            else{
                long tongTien = Integer.parseInt(soLuong) * Integer.parseInt(donGia) * diff;
                txtTongTien.setText(String.valueOf(tongTien));
            }
        }
    }//GEN-LAST:event_btnTinhTongTienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThueForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnThue;
    private javax.swing.JButton btnTinhTongTien;
    private javax.swing.JComboBox<String> cbSize;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lbDonGia;
    private javax.swing.JLabel lbNgayThue;
    private javax.swing.JLabel lbNgayTra;
    private javax.swing.JLabel lbNgayTra1;
    private javax.swing.JLabel lbSize;
    private javax.swing.JLabel lbSoLuong;
    private javax.swing.JLabel lbTongTien;
    private javax.swing.JTextField txtDonGia;
    private java.awt.TextField txtNgayThue;
    private java.awt.TextField txtNgayTra;
    private java.awt.TextField txtSoLuong;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtmasv;
    // End of variables declaration//GEN-END:variables
}
